### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by coderobe** [reswitched/Mephisto#18]
I was not able to find a license - https://github.com/reswitched/Mephisto/blob/master/GdbStub.h#L2 is licensed under the GPLv2 though

Could you please shed some light on the licensing status of this project?

**Comment by SomeoneWeird** [comment]
There is a [LICENSE](https://github.com/reswitched/Mephisto/blob/master/LICENSE.txt) file in the repository.

**Comment by coderobe** [comment]
My bad - GitHub did not detect the license and i didn't find it in the README or file headers;
Problem solved, thanks.
