### ISSUE TITLE
Please don't stop the development of this beautiful masterpiece of software

### ISSUE THREAD

**Issue by skybldev** [reswitched/Mephisto#26]
I and literally 50+% of the internet want an NS emulator, and you're the guys who are pioneers of NS emulator technology. Please don't let this die, this is an active hope... and many people depend on you guys :D

**Comment by 0x8080** [comment]
This section is reserved for issues, nothing else. If you want to express your thoughts for this emulator and its devs please do it in the community (via Discord, Reddit, etc.), and if there arn't any then make one.
